apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/acmiel-rhtap/cachi2-rpm?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: (event == "pull_request" && target_branch == "e2e") || (event == "push" && target_branch.startsWith("gh-readonly-queue/e2e/"))
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cachi2-rpm-1
    appstudio.openshift.io/component: acmiel-rhtap-cachi2-rpm
    pipelines.appstudio.openshift.io/type: build
  name: acmiel-rhtap-cachi2-rpm-on-pull-request
  namespace: acmiel-tenant
spec:
  params:
    - name: SOURCE_URL
      value: '{{source_url}}'
    - name: REVISION
      value: '{{revision}}'
  pipelineSpec:
    params:
      - name: SOURCE_URL
        type: string
      - name: REVISION
        type: string
    tasks:
    - name: test
      params:
        - name: SOURCE_URL
          value: $(params.SOURCE_URL)
        - name: REVISION
          value: $(params.REVISION)
      taskSpec:
        params:
          - name: SOURCE_URL
            type: string
          - name: REVISION
            type: string
        steps:
          - name: test
            image: registry.access.redhat.com/ubi9/ubi-micro:latest
            script: |
              set -x
              echo $(params.SOURCE_URL)
              echo $(params.REVISION)
status: {}
